### ISSUE TITLE
.DS_Store is not a valid directory

### ISSUE THREAD

**Issue by MrJarnould** [thehappydinoa/iOSRestrictionBruteForce#10]
I'm getting this error.  Any help would be appreciated.

```
python ioscrack.py -m

 iOSRestrictionBruteForce
 Written by thehappydinoa

Please navigate to `~/Library/Application\ Support/MobileSync/Backup/\`

Copy the contents of `~/Library/Application\ Support/MobileSync/Backup/` to `/Users/MrJarnould/iOSRestrictionBruteForce/backup`

I'll wait

Press [return] to continue
Traceback (most recent call last):
  File "ioscrack.py", line 216, in <module>
    main()
  File "ioscrack.py", line 203, in main
    mojave_help()
  File "ioscrack.py", line 148, in mojave_help
    crack_hashes(find_hashes(path=path))
  File "ioscrack.py", line 115, in find_hashes
    devices.append(iDevice(device_path))
  File "ioscrack.py", line 62, in __init__
    raise ValueError("%s is not a valid directory" % path)
ValueError: /Users/MrJarnould/iOSRestrictionBruteForce/backup/.DS_Store is not a valid directory
```

**Comment by thehappydinoa** [comment]
Fixed in 89723e7
