### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by yagee** [thehappydinoa/iOSRestrictionBruteForce#3]
I am trying to start script but it doesn't work. There is some error:

Looking for backups in /Users/r.ryzhikov/Desktop/back/... Directory Found
Traceback (most recent call last):
  File "ioscrack.py", line 310, in <module>
    main()
  File "ioscrack.py", line 299, in main
    findHashes(args.backup)
  File "ioscrack.py", line 278, in findHashes
    device = idevice(path + bkup_dir)
  File "ioscrack.py", line 76, in __init__
    self.findSecretKeySalt()
  File "ioscrack.py", line 85, in findSecretKeySalt
    self.secret64 = line_list[6][1:29]
IndexError: list index out of range

**Comment by thehappydinoa** [comment]
That means your backup is encrypted, I'm sorry, but I cannot help with that.

**Comment by yagee** [comment]
My mistake, sorry for that.

**Comment by thehappydinoa** [comment]
It's all good, it's a common thing, I'll add detection
