### ISSUE TITLE
'NoneType' object has no attribute 'readlines'

### ISSUE THREAD

**Issue by Nirajn2311** [thehappydinoa/iOSRestrictionBruteForce#6]
Sorry for the late reply, but now there is a new error.
```
Nandish@Niraj MINGW64 ~/Desktop/VSCode/python/iOSRestrictionBruteForce (master)
$ python ioscrack.py -a

 iOSRestrictionBruteForce
 Written by thehappydinoa


Looking for backups in C:\Users\Nandish\AppData\Roaming\Apple Computer\MobileSync\Backup\/... Directory Found
Found 9736e0d3a918a53bac6d16f1f647c435b44a41f5
Traceback (most recent call last):
  File "ioscrack.py", line 32, in <module>
    main()
  File "ioscrack.py", line 18, in main
    crackHashes(findHashes(BACKUP_PATHS))
  File "C:\Users\Nandish\Desktop\VSCode\python\iOSRestrictionBruteForce\ioscrack\parse.py", line 17, in findHashes
    device = iDevice(path + bkup_dir)
  File "C:\Users\Nandish\Desktop\VSCode\python\iOSRestrictionBruteForce\ioscrack\idevice.py", line 22, in __init__
    self.findSecretKeySalt()
  File "C:\Users\Nandish\Desktop\VSCode\python\iOSRestrictionBruteForce\ioscrack\idevice.py", line 37, in findSecretKeySalt
    line_list = passfile.readlines()
AttributeError: 'NoneType' object has no attribute 'readlines'
```

**Comment by thehappydinoa** [comment]
Fixed in 8d0fb864787cf1e67e7ecec423470c26d01e0a65
