### ISSUE TITLE
libimobiledevice backup does not work with ioscrack

### ISSUE THREAD

**Issue by Anonyvius** [thehappydinoa/iOSRestrictionBruteForce#7]
just backed up my iphone with idevicebackup2 and everything worked fine. The problem is when i start ioscrack.py `python3 ioscrack.py -a -b /root/iOSRestrictionBruteForce/backups/*` i get the error: 

> Looking for backups in /root/iOSRestrictionBruteForce/backups/47146e46bd127ee76c53d24a50233757188c54bd/...
Directory Found
Found e7
Traceback (most recent call last):
  File "ioscrack.py", line 39, in <module>
    main()
  File "ioscrack.py", line 31, in main
    handleArgs()
  File "ioscrack.py", line 15, in handleArgs
    crackHashes(findHashes(path=args.backup))
  File "/root/iOSRestrictionBruteForce/ioscrack/parse.py", line 22, in findHashes
    device = iDevice(path + bkup_dir)
  File "/root/iOSRestrictionBruteForce/ioscrack/idevice.py", line 26, in _init_
    raise ValueError("%s does not appear to contain a backup" % path)
ValueError: /root/iOSRestrictionBruteForce/backups/47146e46bd127ee76c53d24a50233757188c54bd/e7 does not appear to contain a backup
root@Anonyvius:~/iOSRestrictionBruteForce#

Got anything to fix this? And what OS are you using?

*~/backups/ is the folder where the idevicebackups get saved

I also ran the test command `python3 ioscrack.py -t` and it said everything was ok.

**Comment by Anonyvius** [comment]
Also  didn't worked. Got an error, will post later, around 8pm.

**Comment by Anonyvius** [comment]
Getting this error:

`root@Anonyvius:~/iOSRestrictionBruteForce# python3 ioscrack.py -b /root/iOSRestrictionBruteForce/backups/

Looking for backups in /root/iOSRestrictionBruteForce/backups/...
Directory Found
Found 47146e46bd127ee76c53d24a50233757188c54bd
Traceback (most recent call last):
  File "ioscrack.py", line 39, in <module>
    main()
  File "ioscrack.py", line 31, in main
    handleArgs()
  File "ioscrack.py", line 15, in handleArgs
    crackHashes(findHashes(path=args.backup))
  File "/root/iOSRestrictionBruteForce/ioscrack/parse.py", line 22, in findHashes
    device = iDevice(path + bkup_dir)
  File "/root/iOSRestrictionBruteForce/ioscrack/idevice.py", line 24, in __init__
    self.findSecretKeySalt()
  File "/root/iOSRestrictionBruteForce/ioscrack/idevice.py", line 37, in findSecretKeySalt
    self.findSecretKeySalt(newPath=(not newPath))
  File "/root/iOSRestrictionBruteForce/ioscrack/idevice.py", line 35, in findSecretKeySalt
    self.getSecretFromFile(path)
  File "/root/iOSRestrictionBruteForce/ioscrack/idevice.py", line 41, in getSecretFromFile
    line_list = readPlist(path)
  File "/usr/lib/python3.6/plistlib.py", line 164, in readPlist
    dict_type=_InternalDict)
  File "/usr/lib/python3.6/plistlib.py", line 1009, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file
root@Anonyvius:~/iOSRestrictionBruteForce# `

**Comment by thehappydinoa** [comment]
Would you mind sending the folder structure and the `Info.plist`?

**Comment by Anonyvius** [comment]
Will du, when I'm back from school. Around 1:30pm

**Comment by Anonyvius** [comment]
What do you mean with sending the folder structure? But i got the `info.plist` as an txt, because `.plist`  isn´t supported.


[info.txt](https://github.com/thehappydinoa/iOSRestrictionBruteForce/files/2053687/info.txt)

**Comment by Anonyvius** [comment]
I realy have no idea, iwas thinking about creating my backups inside the folder that the automatic function is using

**Comment by thehappydinoa** [comment]
I have no idea why that isn't working maybe try manual input

**Comment by Anonyvius** [comment]
I will try. What about the `python3 ioscrack.py -a` Function? In which file is saved the path it uses? I could try rewriting this file, so it automatically searches inside my backup folder.

**Comment by Anonyvius** [comment]
For the manual input? Where do i find the "Secret" key?

**Comment by Anonyvius** [comment]
I edited the 'paths.py' to instantly look inside my custom directory. Now getting the same error as I were using the '-b' option:

> root@Anonyvius:~/iOSRestrictionBruteForce# python3 ioscrack.py -a

 iOSRestrictionBruteForce
 Written by thehappydinoa


Looking for backups in /root/iOSRestrictionBruteForce/backups/...
Directory Found
Found 47146e46bd127ee76c53d24a50233757188c54bd
Traceback (most recent call last):
  File "ioscrack.py", line 39, in <module>
    main()
  File "ioscrack.py", line 31, in main
    handleArgs()
  File "ioscrack.py", line 17, in handleArgs
    crackHashes(findHashes())
  File "/root/iOSRestrictionBruteForce/ioscrack/parse.py", line 22, in findHashes
    device = iDevice(path + bkup_dir)
  File "/root/iOSRestrictionBruteForce/ioscrack/idevice.py", line 24, in __init__
    self.findSecretKeySalt()
  File "/root/iOSRestrictionBruteForce/ioscrack/idevice.py", line 37, in findSecretKeySalt
    self.findSecretKeySalt(newPath=(not newPath))
  File "/root/iOSRestrictionBruteForce/ioscrack/idevice.py", line 35, in findSecretKeySalt
    self.getSecretFromFile(path)
  File "/root/iOSRestrictionBruteForce/ioscrack/idevice.py", line 41, in getSecretFromFile
    line_list = readPlist(path)
  File "/usr/lib/python3.6/plistlib.py", line 164, in readPlist
    dict_type=_InternalDict)
  File "/usr/lib/python3.6/plistlib.py", line 1009, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file
root@Anonyvius:~/iOSRestrictionBruteForce#

**Comment by thehappydinoa** [comment]
Is the backup encrypted?

**Comment by Anonyvius** [comment]
whooooops ( •_•)

**Comment by thehappydinoa** [comment]
Would you make a PR for it?

**Comment by Anonyvius** [comment]
k, did it

**Comment by thehappydinoa** [comment]
Did you submit it?
